server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 
  jooq:
    sql-dialect: MYSQL
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

quartzTask: false  
    

